name: Test Good is Good

on:
  workflow_run:
    workflows:
      - Test with NATS
    types:
      - completed

jobs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    good:
        runs-on: ubuntu-latest
        steps:
            - name: ok
              run: echo "I am good"